apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      name: apache
      labels:
        app: apache-server
    spec:
      containers:
      - name: apache
        image: nageswarareddy/apache:v1
        tty: true

