apiVersion: v1
kind: Service
metadata:
  name: apache-expose
  labels:
    name: apache-port-expose
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30187
      name: http
  selector:
    app: apache-server
